/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waluty;

/**
 *
 * @author jurczyk
 */
public class KonwerterFrame extends javax.swing.JFrame {

    /**
     * Creates new form KonwerterFrame
     */
    public KonwerterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupa2 = new javax.swing.ButtonGroup();
        grupa1 = new javax.swing.ButtonGroup();
        kwota1 = new javax.swing.JTextField();
        etykieta2 = new javax.swing.JLabel();
        kwota2 = new javax.swing.JTextField();
        przyciskPrzelicz12 = new javax.swing.JButton();
        przyciskPrzelicz21 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radio2PLN = new javax.swing.JRadioButton();
        radio2EUR = new javax.swing.JRadioButton();
        radio2USD = new javax.swing.JRadioButton();
        radio2GBP = new javax.swing.JRadioButton();
        etykieta1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radio1PLN = new javax.swing.JRadioButton();
        radio1EUR = new javax.swing.JRadioButton();
        radio1USD = new javax.swing.JRadioButton();
        radio1GBP = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konwerter Walut v.1.0");

        kwota1.setText("0");

        etykieta2.setText("EUR");

        kwota2.setText("0");

        przyciskPrzelicz12.setText("przelicz >>");
        przyciskPrzelicz12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskPrzelicz12ActionPerformed(evt);
            }
        });

        przyciskPrzelicz21.setText("<< przelicz");
        przyciskPrzelicz21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskPrzelicz21ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "waluta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        grupa2.add(radio2PLN);
        radio2PLN.setText("PLN");
        radio2PLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete2(evt);
            }
        });

        grupa2.add(radio2EUR);
        radio2EUR.setSelected(true);
        radio2EUR.setText("EUR");
        radio2EUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete2(evt);
            }
        });

        grupa2.add(radio2USD);
        radio2USD.setText("USD");
        radio2USD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete2(evt);
            }
        });

        grupa2.add(radio2GBP);
        radio2GBP.setText("GBP");
        radio2GBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete2(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio2PLN)
                    .addComponent(radio2EUR)
                    .addComponent(radio2USD)
                    .addComponent(radio2GBP))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radio2PLN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio2EUR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio2USD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio2GBP))
        );

        etykieta1.setText("PLN");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "waluta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        grupa1.add(radio1PLN);
        radio1PLN.setSelected(true);
        radio1PLN.setText("PLN");
        radio1PLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete1(evt);
            }
        });

        grupa1.add(radio1EUR);
        radio1EUR.setText("EUR");
        radio1EUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete1(evt);
            }
        });

        grupa1.add(radio1USD);
        radio1USD.setText("USD");
        radio1USD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete1(evt);
            }
        });

        grupa1.add(radio1GBP);
        radio1GBP.setText("GBP");
        radio1GBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaktualnijEtykiete1(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio1PLN)
                    .addComponent(radio1EUR)
                    .addComponent(radio1USD)
                    .addComponent(radio1GBP))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radio1PLN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio1EUR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio1USD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio1GBP))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(kwota1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(etykieta1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kwota2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(etykieta2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(przyciskPrzelicz12)
                        .addGap(35, 35, 35)
                        .addComponent(przyciskPrzelicz21)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kwota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etykieta2))
                    .addComponent(etykieta1)
                    .addComponent(kwota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przyciskPrzelicz12)
                    .addComponent(przyciskPrzelicz21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private float konwertuj(String tekst) {
        float liczba = 0.0f;
        try{
            liczba = Float.parseFloat(tekst);
        }catch(NumberFormatException e){
            System.err.println("Błędna kwota!");
        }
        return liczba;
    }
    
    private float wyliczPrzelicznik() {
        float przelicznik1 = 1.0f;
        if(radio1PLN.isSelected()) przelicznik1 = 1.0f;
        else if(radio1EUR.isSelected()) przelicznik1 = EUR2PLN;
        else if(radio1USD.isSelected()) przelicznik1 = USD2PLN;
        else if(radio1GBP.isSelected()) przelicznik1 = GBP2PLN;

        float przelicznik2 = 1.0f;
        if(radio2PLN.isSelected()) przelicznik2 = 1.0f;
        else if(radio2EUR.isSelected()) przelicznik2 = EUR2PLN;
        else if(radio2USD.isSelected()) przelicznik2 = USD2PLN;
        else if(radio2GBP.isSelected()) przelicznik2 = GBP2PLN;

        return przelicznik2 / przelicznik1;
    }
    
    private void przyciskPrzelicz12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskPrzelicz12ActionPerformed
        String tekst = kwota1.getText();
        float liczba = konwertuj(tekst);
        float przelicznik = wyliczPrzelicznik();
        liczba = liczba / przelicznik;
        kwota2.setText(""+liczba);      
    }//GEN-LAST:event_przyciskPrzelicz12ActionPerformed

    private void przyciskPrzelicz21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskPrzelicz21ActionPerformed
        String tekst = kwota2.getText();
        float liczba = konwertuj(tekst);
        float przelicznik = wyliczPrzelicznik();
        liczba = liczba * przelicznik;
        kwota1.setText(""+liczba);
    }//GEN-LAST:event_przyciskPrzelicz21ActionPerformed

    private void uaktualnijEtykiete2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uaktualnijEtykiete2
        javax.swing.JRadioButton radio = (javax.swing.JRadioButton)evt.getSource();
        etykieta2.setText(radio.getText());
    }//GEN-LAST:event_uaktualnijEtykiete2

    private void uaktualnijEtykiete1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uaktualnijEtykiete1
        javax.swing.JRadioButton radio = (javax.swing.JRadioButton)evt.getSource();
        etykieta1.setText(radio.getText());
    }//GEN-LAST:event_uaktualnijEtykiete1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonwerterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonwerterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonwerterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonwerterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonwerterFrame().setVisible(true);
            }
        });
    }

    private final float EUR2PLN = 4.42f;
    private final float USD2PLN = 4.23f;
    private final float GBP2PLN = 5.29f;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etykieta1;
    private javax.swing.JLabel etykieta2;
    private javax.swing.ButtonGroup grupa1;
    private javax.swing.ButtonGroup grupa2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kwota1;
    private javax.swing.JTextField kwota2;
    private javax.swing.JButton przyciskPrzelicz12;
    private javax.swing.JButton przyciskPrzelicz21;
    private javax.swing.JRadioButton radio1EUR;
    private javax.swing.JRadioButton radio1GBP;
    private javax.swing.JRadioButton radio1PLN;
    private javax.swing.JRadioButton radio1USD;
    private javax.swing.JRadioButton radio2EUR;
    private javax.swing.JRadioButton radio2GBP;
    private javax.swing.JRadioButton radio2PLN;
    private javax.swing.JRadioButton radio2USD;
    // End of variables declaration//GEN-END:variables
}
