/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listaOsob;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jurczyk
 */
public class ListaOsobFrame extends javax.swing.JFrame {

    /**
     * Creates new form ListaOsobFrame
     */
    public ListaOsobFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        poleImie = new javax.swing.JTextField();
        poleNazwisko = new javax.swing.JTextField();
        spinnerRok = new javax.swing.JSpinner();
        przyciskDodaj = new javax.swing.JButton();
        przyciskLosuj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        przyciskWypiszLista = new javax.swing.JButton();
        przyciskUsunLista = new javax.swing.JButton();
        przyciskWyczyscLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        przyciskWypiszTabela = new javax.swing.JButton();
        przyciskUsunTabela = new javax.swing.JButton();
        przyciskIWyczyscTabela = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista i Tabela Osób");

        poleImie.setColumns(8);
        poleImie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imię", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel1.add(poleImie);

        poleNazwisko.setColumns(8);
        poleNazwisko.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nazwisko", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel1.add(poleNazwisko);

        spinnerRok.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, null, 1));
        spinnerRok.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rok ur.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 0, 204))); // NOI18N
        jPanel1.add(spinnerRok);

        przyciskDodaj.setText("dodaj");
        przyciskDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskDodajActionPerformed(evt);
            }
        });
        jPanel1.add(przyciskDodaj);

        przyciskLosuj.setText("losowo");
        przyciskLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskLosujActionPerformed(evt);
            }
        });
        jPanel1.add(przyciskLosuj);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 0, 255))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("menu"));

        przyciskWypiszLista.setText("wypisz");
        przyciskWypiszLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskWypiszListaActionPerformed(evt);
            }
        });
        jPanel4.add(przyciskWypiszLista);

        przyciskUsunLista.setText("usuń");
        jPanel4.add(przyciskUsunLista);

        przyciskWyczyscLista.setText("wyczyść");
        jPanel4.add(przyciskWyczyscLista);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        modelListy = new DefaultListModel<String>();
        lista.setModel(modelListy);
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lista);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 0, 255))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("menu"));

        przyciskWypiszTabela.setText("wypisz");
        przyciskWypiszTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskWypiszTabelaActionPerformed(evt);
            }
        });
        jPanel6.add(przyciskWypiszTabela);

        przyciskUsunTabela.setText("usuń");
        przyciskUsunTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskUsunTabelaActionPerformed(evt);
            }
        });
        jPanel6.add(przyciskUsunTabela);

        przyciskIWyczyscTabela.setText("wyczyść");
        przyciskIWyczyscTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskIWyczyscTabelaActionPerformed(evt);
            }
        });
        jPanel6.add(przyciskIWyczyscTabela);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Imię", "Nazwisko", "Rok ur.", "Płeć"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        modelTabeli = (DefaultTableModel)tabela.getModel();
        jScrollPane2.setViewportView(tabela);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przyciskDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskDodajActionPerformed
        String imie = poleImie.getText();
        String nazwisko = poleNazwisko.getText();
        Number wartosc = (Number)spinnerRok.getValue();
        int rok_ur = 2000;
        if(wartosc != null) {
            rok_ur = wartosc.intValue();
        } 
        
        String linia = imie + " " + nazwisko + " ur. "+rok_ur;
        
        System.out.println("Dodaję: " + linia);        
        modelListy.addElement(linia);
        
         Random gen = new Random();
        int ile = modelTabeli.getRowCount();
        Object[] wiersz = { ile+1, imie, nazwisko, rok_ur, gen.nextBoolean() };
        modelTabeli.addRow(wiersz);
    }//GEN-LAST:event_przyciskDodajActionPerformed

    private void przyciskLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskLosujActionPerformed
        Random gen = new Random();
        String[] imiona = { "Achacy", "Bonifacy", "Cezary", "Dionizy", "Eustachy" };
        String[] nazwiska = { "Kmicic", "Wołodyjowski", "Skrzetuski", "Zagłoba", "Tuhajbejowicz", "Kramarz", "Laszkowski"};
        
        poleImie.setText( imiona[ gen.nextInt(imiona.length)]);
        poleNazwisko.setText( nazwiska[ gen.nextInt(nazwiska.length)]);
//        spinnerRok.setValue(new Integer(1900 + gen.nextInt(115)));
        spinnerRok.setValue(1900 + gen.nextInt(115));
    }//GEN-LAST:event_przyciskLosujActionPerformed

    private void przyciskWypiszTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskWypiszTabelaActionPerformed
        int ilew = modelTabeli.getRowCount();
        int ilek = modelTabeli.getColumnCount();
        
        System.out.println("Tabela:");
        System.out.println("========================");
        for(int i = 0; i < ilew; i++){
            String wiersz = " -> ";
            for(int j = 0; j < ilek; j++)
                wiersz += " " + modelTabeli.getValueAt(i, j);
            System.out.println(wiersz);
        }
        System.out.println("========================");
        
    }//GEN-LAST:event_przyciskWypiszTabelaActionPerformed

    private void przyciskUsunTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskUsunTabelaActionPerformed
        int[] wiersze = tabela.getSelectedRows();
        for(int i = wiersze.length-1; i >=0; i--){
//        for(int i = 0; i <wiersze.length; i++){
            modelTabeli.removeRow(wiersze[i]);
        }
    }//GEN-LAST:event_przyciskUsunTabelaActionPerformed

    private void przyciskWypiszListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskWypiszListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przyciskWypiszListaActionPerformed

    private void przyciskIWyczyscTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskIWyczyscTabelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przyciskIWyczyscTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaOsobFrame().setVisible(true);
            }
        });
    }

    private javax.swing.DefaultListModel<String> modelListy;
    private DefaultTableModel modelTabeli;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField poleImie;
    private javax.swing.JTextField poleNazwisko;
    private javax.swing.JButton przyciskDodaj;
    private javax.swing.JButton przyciskIWyczyscTabela;
    private javax.swing.JButton przyciskLosuj;
    private javax.swing.JButton przyciskUsunLista;
    private javax.swing.JButton przyciskUsunTabela;
    private javax.swing.JButton przyciskWyczyscLista;
    private javax.swing.JButton przyciskWypiszLista;
    private javax.swing.JButton przyciskWypiszTabela;
    private javax.swing.JSpinner spinnerRok;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
