
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kkramarz
 */
public class TabelaIlista extends javax.swing.JFrame {

    /**
     * Creates new form TabelaIlista
     */
    public TabelaIlista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        losuj10Button = new javax.swing.JPanel();
        poleImie = new javax.swing.JTextField();
        poleNazwisko = new javax.swing.JTextField();
        spinRok = new javax.swing.JSpinner();
        dodajButton = new javax.swing.JButton();
        losujButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        wypiszLista = new javax.swing.JButton();
        usunLista = new javax.swing.JButton();
        zmienLista = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        wypiszLista1 = new javax.swing.JButton();
        usunLista1 = new javax.swing.JButton();
        zmienLista1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        widokTabeli = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("lista i tabela");
        setPreferredSize(new java.awt.Dimension(786, 451));

        poleImie.setColumns(8);
        poleImie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "imie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        losuj10Button.add(poleImie);

        poleNazwisko.setColumns(8);
        poleNazwisko.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "nazwisko", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        losuj10Button.add(poleNazwisko);

        spinRok.setModel(new javax.swing.SpinnerNumberModel(1950, null, null, 1));
        spinRok.setBorder(javax.swing.BorderFactory.createTitledBorder("rokUrodzenia"));
        losuj10Button.add(spinRok);

        dodajButton.setText("dodaj");
        dodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajButtonActionPerformed(evt);
            }
        });
        losuj10Button.add(dodajButton);

        losujButton.setText("losuj");
        losujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losujButtonActionPerformed(evt);
            }
        });
        losuj10Button.add(losujButton);

        jButton1.setText("losuj x 10");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        losuj10Button.add(jButton1);

        getContentPane().add(losuj10Button, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("xx"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("dół"));

        wypiszLista.setText("wypisz");
        wypiszLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wypiszListaActionPerformed(evt);
            }
        });
        jPanel5.add(wypiszLista);

        usunLista.setText("usun");
        usunLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunListaActionPerformed(evt);
            }
        });
        jPanel5.add(usunLista);

        zmienLista.setText("czysc");
        jPanel5.add(zmienLista);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Góra"));
        jPanel6.setPreferredSize(new java.awt.Dimension(378, 102));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        modelListy = new DefaultListModel<>();
        lista.setModel(modelListy);
        jScrollPane1.setViewportView(lista);

        jPanel6.add(jScrollPane1);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("dół"));

        wypiszLista1.setText("wypisz");
        jPanel8.add(wypiszLista1);

        usunLista1.setText("usun");
        usunLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunLista1ActionPerformed(evt);
            }
        });
        jPanel8.add(usunLista1);

        zmienLista1.setText("czysc");
        jPanel8.add(zmienLista1);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Góra"));
        jPanel9.setPreferredSize(new java.awt.Dimension(378, 102));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        widokTabeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nr", "imie", "nazwisko3", "rok", "obecny"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        widokTabeli.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableModel = ( DefaultTableModel)widokTabeli.getModel();
        jScrollPane2.setViewportView(widokTabeli);

        jPanel9.add(jScrollPane2);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wypiszListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wypiszListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wypiszListaActionPerformed

    private void usunListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usunListaActionPerformed

    private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajButtonActionPerformed
      dodaj();
    }//GEN-LAST:event_dodajButtonActionPerformed

    private void losujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losujButtonActionPerformed
   String[] imiona = {"Achacy", "boniufacy"};
          String[] nazwiska = {"Kleks", "Skrzetuski"};
          Random random = new Random();
          poleImie.setText(imiona[random.nextInt(imiona.length)]);
            poleNazwisko.setText(imiona[random.nextInt(imiona.length)]);
          //  spinRok.setValue(new Integer(1950+random.nextInt(51)));
          spinRok.setValue(1950+random.nextInt(51));
          
          
    }//GEN-LAST:event_losujButtonActionPerformed
private void dodaj(){
    String imie = poleImie.getText();
      String nazwisko = poleNazwisko.getText();
      Number wartosc = (Number) spinRok.getValue();
      int rok_ur = 1950;
      if(wartosc != null){
          rok_ur = wartosc.intValue();
              
          
          
      }
      
      
      String osoba = imie + "  " + nazwisko + "  " + rok_ur;
        System.out.println(osoba);
        modelListy.addElement(osoba);
        DefaultTableModel tm = ( DefaultTableModel)widokTabeli.getModel();
        int ile = tm.getRowCount();
          Object[] wiersz = {ile+1, imie, nazwisko, rok_ur, true};
          tm.addRow(wiersz);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      for (int i = 0; i<10;i++){
          dodaj();
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usunLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunLista1ActionPerformed
     int[] wiersze =  widokTabeli.getSelectedRows();
     for( int i = wiersze.length - 1; i>=0; i--){
         tableModel.removeRow(wiersze[i]);
     }
     
     while(true){
         
         int w = widokTabeli.getSelectedRow();
         if(w==-1)return;
         tableModel.removeRow(w);
         
     }
     
    }//GEN-LAST:event_usunLista1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaIlista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaIlista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaIlista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaIlista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaIlista().setVisible(true);
            }
        });
    }
    
    private DefaultListModel<String> modelListy;
    
    private DefaultTableModel tableModel ;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JPanel losuj10Button;
    private javax.swing.JButton losujButton;
    private javax.swing.JTextField poleImie;
    private javax.swing.JTextField poleNazwisko;
    private javax.swing.JSpinner spinRok;
    private javax.swing.JButton usunLista;
    private javax.swing.JButton usunLista1;
    private javax.swing.JTable widokTabeli;
    private javax.swing.JButton wypiszLista;
    private javax.swing.JButton wypiszLista1;
    private javax.swing.JButton zmienLista;
    private javax.swing.JButton zmienLista1;
    // End of variables declaration//GEN-END:variables
}
