/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daty;

/**
 *
 * @author Krzysiek
 */
public class DatyKonsola extends javax.swing.JFrame {

    /**
     * Creates new form DatyKonsola
     */
    public DatyKonsola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonZwieksz = new javax.swing.JButton();
        buttonZmniejsz = new javax.swing.JButton();
        textFieldData = new javax.swing.JTextField();
        comboBoxWartosc = new javax.swing.JComboBox<>();
        checkBx31dni = new javax.swing.JCheckBox();
        textFieldDzien = new javax.swing.JTextField();
        textFieldMiesiac = new javax.swing.JTextField();
        textFieldRok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonWpisz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonZwieksz.setText("zwieksz");
        buttonZwieksz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZwiekszActionPerformed(evt);
            }
        });

        buttonZmniejsz.setText("zmniejsz");
        buttonZmniejsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmniejszActionPerformed(evt);
            }
        });

        textFieldData.setColumns(20);
        textFieldData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA")));
        textFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDataActionPerformed(evt);
            }
        });

        comboBoxWartosc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dzien", "miesiąc", "rok" }));

        checkBx31dni.setText("31 dni");

        textFieldDzien.setColumns(8);

        textFieldMiesiac.setColumns(8);

        textFieldRok.setColumns(8);

        jLabel1.setText("dzien");

        jLabel2.setText("miesiac");

        jLabel3.setText("rok");

        buttonWpisz.setText("wpisz");
        buttonWpisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWpiszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkBx31dni)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(textFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82)
                                    .addComponent(textFieldMiesiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(comboBoxWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonZwieksz)
                                .addComponent(buttonZmniejsz))
                            .addGap(39, 39, 39)
                            .addComponent(buttonWpisz)
                            .addGap(82, 82, 82)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldDzien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDzien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldMiesiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(checkBx31dni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZmniejsz)
                    .addComponent(comboBoxWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(buttonWpisz)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonZwieksz)
                        .addGap(33, 33, 33))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZwiekszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZwiekszActionPerformed
        int coZmieniamy = sprawdzComboBox();
        Integer dzien = waliduj(textFieldDzien);
        Integer miesiac = waliduj(textFieldMiesiac);
        boolean czy31 = checkBx31dni.isSelected();
        switch (coZmieniamy) {
            case 1:

                if (czy31) {
                    dzien++;
                    if (dzien > 31) {
                        dzien = 1;
                        miesiac++;
                    }
                } else {
                    dzien++;
                    if (dzien > 30) {
                        dzien = 1;
                        miesiac++;
                    }
                }

                break;
            case 2:
                break;
            case 3:
                break;
        }

        textFieldDzien.setText(String.valueOf(dzien));
        textFieldMiesiac.setText(String.valueOf(miesiac));
        wpisz();
    }//GEN-LAST:event_buttonZwiekszActionPerformed

    private void buttonZmniejszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmniejszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonZmniejszActionPerformed

    private void textFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDataActionPerformed

    }//GEN-LAST:event_textFieldDataActionPerformed

    private void buttonWpiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWpiszActionPerformed
        wpisz();
    }//GEN-LAST:event_buttonWpiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatyKonsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatyKonsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatyKonsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatyKonsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatyKonsola().setVisible(true);
            }
        });
    }

    private void wpisz() {
        String data = textFieldDzien.getText() + "/" + textFieldMiesiac.getText() + "/" + textFieldRok.getText();
        textFieldData.setText(data);
    }

    private Integer waliduj(javax.swing.JTextField textField) {
        Integer liczba = 0;
        try {
            liczba = Integer.valueOf(textField.getText());
        } catch (NumberFormatException e) {
            textField.setText("0");
            e.printStackTrace();
        }
        return liczba;
    }

    private int sprawdzComboBox() {
        int coSprawdzamy = 0;
        String co = (String) comboBoxWartosc.getSelectedItem();
        switch (co) {
            case "dzien":
                coSprawdzamy = 1;
                break;
            case "miesiąc":
                coSprawdzamy = 2;
                break;
            case "rok":
                coSprawdzamy = 3;
                break;
        }
        return coSprawdzamy;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonWpisz;
    private javax.swing.JButton buttonZmniejsz;
    private javax.swing.JButton buttonZwieksz;
    private javax.swing.JCheckBox checkBx31dni;
    private javax.swing.JComboBox<String> comboBoxWartosc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldData;
    private javax.swing.JTextField textFieldDzien;
    private javax.swing.JTextField textFieldMiesiac;
    private javax.swing.JTextField textFieldRok;
    // End of variables declaration//GEN-END:variables
}
