
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Krzysiek
 */
public class KinoPanel extends javax.swing.JFrame {

    /**
     * Creates new form KinoPanel
     */
    public KinoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupWiek = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textFieldFilm = new javax.swing.JTextField();
        buttonWypisz = new javax.swing.JButton();
        buttonWyczysc = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        textFieldRok = new javax.swing.JTextField();
        radioButton7 = new javax.swing.JRadioButton();
        radioButton12 = new javax.swing.JRadioButton();
        radioButtonBO = new javax.swing.JRadioButton();
        radioButton18 = new javax.swing.JRadioButton();
        radioButton16 = new javax.swing.JRadioButton();
        textFieldOpis = new javax.swing.JTextField();
        checkBoxHorror = new javax.swing.JCheckBox();
        checkBoxKomedia = new javax.swing.JCheckBox();
        checkBoxAnimowany = new javax.swing.JCheckBox();
        buttonGeneruj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        widokLista = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        widokTabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonUsun = new javax.swing.JButton();
        buttonDodaj = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        buttonUsun1 = new javax.swing.JButton();
        buttonDodaj1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Szczegóły filmu"));

        textFieldFilm.setColumns(8);
        textFieldFilm.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Film"));

        buttonWypisz.setText("wypisz");
        buttonWypisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWypiszActionPerformed(evt);
            }
        });

        buttonWyczysc.setText("wyczysc");
        buttonWyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWyczyscActionPerformed(evt);
            }
        });

        buttonStop.setText("STOP");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        textFieldRok.setColumns(8);
        textFieldRok.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Rok"));

        buttonGroupWiek.add(radioButton7);
        radioButton7.setText("7");

        buttonGroupWiek.add(radioButton12);
        radioButton12.setText("12");

        buttonGroupWiek.add(radioButtonBO);
        radioButtonBO.setSelected(true);
        radioButtonBO.setText("b.o.");

        buttonGroupWiek.add(radioButton18);
        radioButton18.setText("18");

        buttonGroupWiek.add(radioButton16);
        radioButton16.setText("16");

        textFieldOpis.setEditable(false);
        textFieldOpis.setColumns(8);
        textFieldOpis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "O P I S"));

        checkBoxHorror.setText("horror");
        checkBoxHorror.setToolTipText("");
        checkBoxHorror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxHorrorActionPerformed(evt);
            }
        });

        checkBoxKomedia.setText("komedia");
        checkBoxKomedia.setToolTipText("");
        checkBoxKomedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxKomediaActionPerformed(evt);
            }
        });

        checkBoxAnimowany.setText("animowany");
        checkBoxAnimowany.setToolTipText("");
        checkBoxAnimowany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAnimowanyActionPerformed(evt);
            }
        });

        buttonGeneruj.setText("GENERUJ");
        buttonGeneruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textFieldFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(textFieldRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioButtonBO)
                        .addGap(10, 10, 10)
                        .addComponent(radioButton7)
                        .addGap(10, 10, 10)
                        .addComponent(radioButton12)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton16)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(buttonWyczysc)
                        .addGap(31, 31, 31)
                        .addComponent(buttonWypisz)
                        .addGap(30, 30, 30)
                        .addComponent(buttonGeneruj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonStop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkBoxHorror)
                .addGap(18, 18, 18)
                .addComponent(checkBoxKomedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxAnimowany)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonBO)
                            .addComponent(radioButton7)
                            .addComponent(radioButton12)
                            .addComponent(radioButton16)
                            .addComponent(radioButton18))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonWyczysc)
                            .addComponent(buttonWypisz)
                            .addComponent(buttonStop)
                            .addComponent(buttonGeneruj))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxAnimowany)
                            .addComponent(checkBoxKomedia)
                            .addComponent(checkBoxHorror))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista filmów"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        modelLista = new DefaultListModel<>();
        widokLista.setModel(modelLista);
        jScrollPane1.setViewportView(widokLista);

        jPanel2.add(jScrollPane1);

        widokTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Rok", "Ograniczenia", "Typ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        modelTabela = (DefaultTableModel)widokTabela.getModel();
        jScrollPane2.setViewportView(widokTabela);

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Akcje"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        buttonUsun.setText("Usuń");
        buttonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunActionPerformed(evt);
            }
        });
        jPanel4.add(buttonUsun);

        buttonDodaj.setText("dodaj do listy");
        buttonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDodajActionPerformed(evt);
            }
        });
        jPanel4.add(buttonDodaj);

        jPanel3.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 69));

        buttonUsun1.setText("Usuń");
        buttonUsun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsun1ActionPerformed(evt);
            }
        });
        jPanel5.add(buttonUsun1);

        buttonDodaj1.setText("dodaj do listy");
        buttonDodaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDodaj1ActionPerformed(evt);
            }
        });
        jPanel5.add(buttonDodaj1);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWyczyscActionPerformed
        textFieldFilm.setText("");
    }//GEN-LAST:event_buttonWyczyscActionPerformed

    private void buttonWypiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWypiszActionPerformed
        String napis = textFieldFilm.getText();
        System.out.println(napis);
    }//GEN-LAST:event_buttonWypiszActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonStopActionPerformed

    private void checkBoxHorrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxHorrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxHorrorActionPerformed

    private void checkBoxKomediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxKomediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxKomediaActionPerformed

    private void checkBoxAnimowanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAnimowanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAnimowanyActionPerformed

    private void buttonGenerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerujActionPerformed

        textFieldOpis.setText("Film " + textFieldFilm.getText() + ", rodzaj: " + writeOutCheckBox() + ", dozwolony od " + writeOutRadioButtons());

    }//GEN-LAST:event_buttonGenerujActionPerformed

    private void buttonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDodajActionPerformed
        modelLista.addElement("Film " + textFieldFilm.getText() + ", rodzaj: " + writeOutCheckBox() + ", dozwolony od " + writeOutRadioButtons());


    }//GEN-LAST:event_buttonDodajActionPerformed

    private void buttonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunActionPerformed
        int[] wierszeDoUsuniecia = widokLista.getSelectedIndices();
        for (int i = wierszeDoUsuniecia.length - 1; i >= 0; i--) {
            modelLista.remove(wierszeDoUsuniecia[i]);
            
        }
    }//GEN-LAST:event_buttonUsunActionPerformed

    private void buttonUsun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsun1ActionPerformed
     // modelTabela.removeRow(widokTabela.getSelectedRow());
      int[] rows = widokTabela.getSelectedRows();
      for(int i =0; i<rows.length;i++){
          modelTabela.removeRow(rows[i]-i);
          System.out.println(rows[i]-i);
      }
      
    }//GEN-LAST:event_buttonUsun1ActionPerformed

    private void buttonDodaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDodaj1ActionPerformed
      modelTabela.addRow(getRowObject());
      
    }//GEN-LAST:event_buttonDodaj1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KinoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KinoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KinoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KinoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KinoPanel().setVisible(true);
            }
        });
    }

    private String writeOutRadioButtons() {

        String rodzaj = "";
        if (checkBoxKomedia.isSelected()) {
            rodzaj += " komedia ";
        }
        if (checkBoxHorror.isSelected()) {
            rodzaj += " horror ";
        }
        if (checkBoxAnimowany.isSelected()) {
            rodzaj += " animowany ";
        }
        return rodzaj;
    }

    private String writeOutCheckBox() {

        String rodzaj = "";
        if (radioButtonBO.isSelected()) {
            rodzaj = " b.o. ";
        }
        if (radioButton7.isSelected()) {
            rodzaj = " 7 ";
        }

        if (radioButton12.isSelected()) {
            rodzaj = " 12 ";
        }

        if (radioButton16.isSelected()) {
            rodzaj = " 16 ";
        }
        if (radioButton18.isSelected()) {
            rodzaj = " 18 ";
        }
        return rodzaj;
    }
private Object[] getRowObject(){
    String film = textFieldFilm.getText();
    String rok =  textFieldRok.getText();
    String ograniczenie =  writeOutRadioButtons();    
    String rodzaj  =  writeOutCheckBox();    
    Object[] row = {film, rok, ograniczenie, rodzaj};
    
    return row;
}
    private DefaultListModel<String> modelLista;
     private DefaultTableModel modelTabela;
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDodaj;
    private javax.swing.JButton buttonDodaj1;
    private javax.swing.JButton buttonGeneruj;
    private javax.swing.ButtonGroup buttonGroupWiek;
    private javax.swing.JButton buttonStop;
    private javax.swing.JButton buttonUsun;
    private javax.swing.JButton buttonUsun1;
    private javax.swing.JButton buttonWyczysc;
    private javax.swing.JButton buttonWypisz;
    private javax.swing.JCheckBox checkBoxAnimowany;
    private javax.swing.JCheckBox checkBoxHorror;
    private javax.swing.JCheckBox checkBoxKomedia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioButton12;
    private javax.swing.JRadioButton radioButton16;
    private javax.swing.JRadioButton radioButton18;
    private javax.swing.JRadioButton radioButton7;
    private javax.swing.JRadioButton radioButtonBO;
    private javax.swing.JTextField textFieldFilm;
    private javax.swing.JTextField textFieldOpis;
    private javax.swing.JTextField textFieldRok;
    private javax.swing.JList<String> widokLista;
    private javax.swing.JTable widokTabela;
    // End of variables declaration//GEN-END:variables
}
