
import java.util.List;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kkramarz
 */
public class OsobyPanel extends javax.swing.JFrame {

    /**
     * Creates new form sdfgsdfg
     */
    public OsobyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPanPani = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        buttonWypiszLista1 = new javax.swing.JButton();
        buttonUsunLista1 = new javax.swing.JButton();
        buttonWyczyscLista1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        widokLista = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonWypiszTabela = new javax.swing.JButton();
        buttonUsunTabela = new javax.swing.JButton();
        buttonWyczyscTabela = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        widokTabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        textFieldNazwisko = new javax.swing.JTextField();
        textFieldImie = new javax.swing.JTextField();
        radioButtonPan = new javax.swing.JRadioButton();
        radioButtonPani = new javax.swing.JRadioButton();
        radioButtonKotek = new javax.swing.JRadioButton();
        spinnerRokUrodzenia = new javax.swing.JSpinner();
        buttonDodaj = new javax.swing.JButton();
        buttonLosuj = new javax.swing.JButton();
        buttonLosuj10 = new javax.swing.JButton();
        buttonConsola = new javax.swing.JButton();
        buttonKoniec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cialo"));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(112, 23));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista"));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "dol"));
        jPanel7.setPreferredSize(new java.awt.Dimension(266, 61));

        buttonWypiszLista1.setText("wypisz");
        buttonWypiszLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWypiszLista1ActionPerformed(evt);
            }
        });
        jPanel7.add(buttonWypiszLista1);

        buttonUsunLista1.setText("usun");
        buttonUsunLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunLista1ActionPerformed(evt);
            }
        });
        jPanel7.add(buttonUsunLista1);

        buttonWyczyscLista1.setText("wyczysc");
        buttonWyczyscLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWyczyscLista1ActionPerformed(evt);
            }
        });
        jPanel7.add(buttonWyczyscLista1);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        modelLista = new DefaultListModel<>();
        widokLista.setModel(modelLista);
        widokLista.setVisibleRowCount(0);
        jScrollPane2.setViewportView(widokLista);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tabela"));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "dol"));
        jPanel4.setPreferredSize(new java.awt.Dimension(266, 60));

        buttonWypiszTabela.setText("wypisz");
        buttonWypiszTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWypiszTabelaActionPerformed(evt);
            }
        });
        jPanel4.add(buttonWypiszTabela);

        buttonUsunTabela.setText("usun");
        buttonUsunTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunTabelaActionPerformed(evt);
            }
        });
        jPanel4.add(buttonUsunTabela);

        buttonWyczyscTabela.setText("wyczysc");
        buttonWyczyscTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWyczyscTabelaActionPerformed(evt);
            }
        });
        jPanel4.add(buttonWyczyscTabela);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(452, 150));

        widokTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nr", "Imie", "Nazwisko", "Rok urodz"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        modelTabela = (DefaultTableModel)widokTabela.getModel();
        jScrollPane3.setViewportView(widokTabela);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("detale"));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 140));

        textFieldNazwisko.setColumns(8);
        textFieldNazwisko.setToolTipText("podaj nazwisko");
        textFieldNazwisko.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)), "Nazwisko", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(textFieldNazwisko);

        textFieldImie.setColumns(8);
        textFieldImie.setToolTipText("podaj imie");
        textFieldImie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)), "Imię", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(textFieldImie);

        buttonGroupPanPani.add(radioButtonPan);
        radioButtonPan.setSelected(true);
        radioButtonPan.setText("Pan");
        jPanel2.add(radioButtonPan);

        buttonGroupPanPani.add(radioButtonPani);
        radioButtonPani.setText("Pani");
        jPanel2.add(radioButtonPani);

        buttonGroupPanPani.add(radioButtonKotek);
        radioButtonKotek.setText("Kotek");
        radioButtonKotek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonKotekActionPerformed(evt);
            }
        });
        jPanel2.add(radioButtonKotek);

        spinnerRokUrodzenia.setModel(new javax.swing.SpinnerNumberModel(1976, 1900, null, 1));
        spinnerRokUrodzenia.setToolTipText("");
        spinnerRokUrodzenia.setBorder(javax.swing.BorderFactory.createTitledBorder("Rok Urodzenia"));
        jPanel2.add(spinnerRokUrodzenia);

        buttonDodaj.setText("dodaj");
        buttonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDodajActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDodaj);

        buttonLosuj.setText("losuj");
        buttonLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLosujActionPerformed(evt);
            }
        });
        jPanel2.add(buttonLosuj);

        buttonLosuj10.setText("losuj x 10");
        buttonLosuj10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLosuj10ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonLosuj10);

        buttonConsola.setText("Consola");
        buttonConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsolaActionPerformed(evt);
            }
        });
        jPanel2.add(buttonConsola);

        buttonKoniec.setText("KONIEC");
        buttonKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKoniecActionPerformed(evt);
            }
        });
        jPanel2.add(buttonKoniec);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsolaActionPerformed
        Number number = (Number) spinnerRokUrodzenia.getValue();

        String napis = "Witamy: " + (radioButtonPan.isSelected() ? radioButtonPan.getText()
                : (radioButtonPani.isSelected() ? radioButtonPani.getText() : radioButtonKotek.getText()))
                + " o imieniu: " + textFieldImie.getText() + ", nazwisko: " + textFieldNazwisko.getText()
                + "  " + number + " a teraz z listy: ";
        System.out.println("#:" + widokLista.getVisibleRowCount());
//        if(lista.getVisibleRowCount()>0){
//            napis += lista.getSelectedValuesList().get(0);
//        }

        System.out.println(napis);
    }//GEN-LAST:event_buttonConsolaActionPerformed

    private void radioButtonKotekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonKotekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonKotekActionPerformed

    private void buttonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDodajActionPerformed
        dodajOsobe();

    }//GEN-LAST:event_buttonDodajActionPerformed

    private void buttonLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLosujActionPerformed
        losujOsobe();

    }//GEN-LAST:event_buttonLosujActionPerformed

    private void buttonLosuj10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLosuj10ActionPerformed
        for (int i = 0; i < 10; i++) {
            losujOsobe();
            dodajOsobe();
        }
    }//GEN-LAST:event_buttonLosuj10ActionPerformed

    private void buttonWyczyscLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWyczyscLista1ActionPerformed
        modelLista.clear();
    }//GEN-LAST:event_buttonWyczyscLista1ActionPerformed

    private void buttonWypiszLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWypiszLista1ActionPerformed
        List<String> listaOsob = widokLista.getSelectedValuesList();

        System.out.println("===========");
        int ileIwerszy = modelLista.getSize();

        for (int i = 0; i < ileIwerszy; i++) {
            System.out.println("   ->" + modelLista.getElementAt(i));

        }
    }//GEN-LAST:event_buttonWypiszLista1ActionPerformed

    private void buttonUsunLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunLista1ActionPerformed
        int[] whichToDelete = widokLista.getSelectedIndices();
        System.out.println(whichToDelete.length);
        for (int i = whichToDelete.length - 1; i >= 0; i--) {
            modelLista.removeElementAt(whichToDelete[i]);

        }
    }//GEN-LAST:event_buttonUsunLista1ActionPerformed

    private void buttonKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKoniecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonKoniecActionPerformed

    private void buttonWypiszTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWypiszTabelaActionPerformed
        int ileIwerszy = modelTabela.getRowCount();
        int ilekolumn = modelTabela.getColumnCount();

        System.out.println("===========");

        for (int i = 0; i < ileIwerszy; i++) {
            for (int j = 0; j < ilekolumn; j++) {
                System.out.print(" " + modelTabela.getValueAt(i, j));

            }
            System.out.println("");
        }
    }//GEN-LAST:event_buttonWypiszTabelaActionPerformed

    private void buttonWyczyscTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWyczyscTabelaActionPerformed
        int wiersze = widokTabela.getRowCount();
        for (int i = wiersze - 1; i >= 0; i--) {
            modelTabela.removeRow(i);
        }
    }//GEN-LAST:event_buttonWyczyscTabelaActionPerformed

    private void buttonUsunTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunTabelaActionPerformed
//        int[] zaznaczoneWiersze = widokTabela.getSelectedRows();
//       for(int i = zaznaczoneWiersze.length-1; i>=0; i--){
//           modelTabela.removeRow(zaznaczoneWiersze[i]);
//       }

        while (!(widokTabela.getSelectedRow() == -1)) {
            modelTabela.removeRow(widokTabela.getSelectedRow());
        }

    }//GEN-LAST:event_buttonUsunTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OsobyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OsobyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OsobyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OsobyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OsobyPanel().setVisible(true);
            }
        });
    }

    private String losujImie() {
        Random rnd = new Random();
        return tablicaImion[rnd.nextInt(tablicaImion.length)];
    }

    private String losujNazwisko() {
        Random rnd = new Random();
        return tablicaNazwisk[rnd.nextInt(tablicaNazwisk.length)];
    }

    private void dodajOsobe() {
        Number number = (Number) spinnerRokUrodzenia.getValue();
        int rok_urodzenia = 1981;
        if (number != null) {
            rok_urodzenia = number.intValue();
        }

        String napis = (radioButtonPan.isSelected() ? radioButtonPan.getText()
                : (radioButtonPani.isSelected() ? radioButtonPani.getText() : radioButtonKotek.getText()))
                + "  " + textFieldImie.getText() + " " + textFieldNazwisko.getText()
                + "  " + rok_urodzenia;

        modelLista.addElement(napis);
        int ile = widokTabela.getRowCount();
        Object[] wiersz = {ile + 1, textFieldImie.getText(), textFieldNazwisko.getText(), rok_urodzenia};
        modelTabela.addRow(wiersz);

    }

    private void losujOsobe() {
        textFieldImie.setText(losujImie());
        textFieldNazwisko.setText(losujNazwisko());
        spinnerRokUrodzenia.setValue(new Integer(1900 + new Random().nextInt(101)));

    }
    private DefaultListModel modelLista;
    private DefaultTableModel modelTabela;
    String[] tablicaImion = {"Anastazy", "Bonifacy", "Korneliusz", "Jurand", "Numeriusz"};
    String[] tablicaNazwisk = {"Kmicic", "Zagłoba", "Skrzetuski", "Nowak", "Tuleya", "Kryże"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConsola;
    private javax.swing.JButton buttonDodaj;
    private javax.swing.ButtonGroup buttonGroupPanPani;
    private javax.swing.JButton buttonKoniec;
    private javax.swing.JButton buttonLosuj;
    private javax.swing.JButton buttonLosuj10;
    private javax.swing.JButton buttonUsunLista1;
    private javax.swing.JButton buttonUsunTabela;
    private javax.swing.JButton buttonWyczyscLista1;
    private javax.swing.JButton buttonWyczyscTabela;
    private javax.swing.JButton buttonWypiszLista1;
    private javax.swing.JButton buttonWypiszTabela;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radioButtonKotek;
    private javax.swing.JRadioButton radioButtonPan;
    private javax.swing.JRadioButton radioButtonPani;
    private javax.swing.JSpinner spinnerRokUrodzenia;
    private javax.swing.JTextField textFieldImie;
    private javax.swing.JTextField textFieldNazwisko;
    private javax.swing.JList<String> widokLista;
    private javax.swing.JTable widokTabela;
    // End of variables declaration//GEN-END:variables
}
